stages:
  - prepare
  - dockerize

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

prepare:
  stage: prepare
  image: node:20-alpine
  before_script:
    - apk add --no-cache jq
  script:
    - RAW_NAME=$(jq -r .name package.json)
    - IMAGE_NAME=$(echo "$RAW_NAME" | sed 's/^@//; s/\//-/g')
    - VERSION=$(jq -r .version package.json)
    - echo "IMAGE_NAME=$IMAGE_NAME" >> build.env
    - echo "VERSION=$VERSION" >> build.env
    - echo "DOCKER_IMAGE=$IMAGE_NAME:$VERSION" >> build.env
  artifacts:
    reports:
      dotenv: build.env
  only:
    - main

dockerize:
  stage: dockerize
  image: docker:27.2.0
  services:
    - name: docker:27.2.0-dind
      alias: docker
  needs:
    - prepare
  script:
    - echo "Building $DOCKER_IMAGE"
    - docker build -t $DOCKER_IMAGE .
    - docker save $DOCKER_IMAGE | gzip > image.tar.gz
  artifacts:
    name: "$DOCKER_IMAGE"
    paths:
      - image.tar.gz
    expire_in: 7 days
  only:
    - main
